export const product = [
  {
    id: '1c2b3d4e-5f6a-7b8c-9d0e-f1a2b3c4d5e6',
    title: "one life graphic T-Shirt",
    image: "/clothes/clothe5.svg",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    rating: 4.5,
    description: "A stylish t-shirt made from high-quality cotton.",
    colors: ["#FF5733", "#33FF57", "#3357FF"],
    thumbnails: [
      "/clothes/clothe5.svg",
      "/clothes/clothe7.svg",
      "/clothes/image6.svg",
    ],
  },
  {
    id: "86dcef78-ca4c-4b19-bb7d-c29af43df927",
    title: "yellow graphic T-Shirt",
    image: "/clothes/clothe1main.jpg",
    price: 26.99,
    originalPrice: 35.99,
    discount: 25,
    rating: 3.5,
    description: "A stylish t-shirt made from high-quality cotton. with a unique design.",
    colors: ["#2ECC71", "#8E44AD", "#3357FF"],
    thumbnails: ["/clothes/clothe1main.jpg", "/clothes/clothe1thumb1.jpg", "/clothes/clothe1thumb2.jpg"],
  },
  {
    id: "b8118102-c781-40bc-8334-46cd3b543087",
    title: "light yellow MIND FEUL T-Shirt",
    image: "/clothes/clothe2main.jpg",
    price: 24.69,
    originalPrice: 25.99,
    discount: 5,
    rating: 4.5,
    description: "A simple yet elegant t-shirt that goes well with any outfit.With text 'MIND FEUL' printed on it.",
    colors: ["#33FF57", "#8E44AD", "#000000"],
    thumbnails: ["/clothes/clothe2main.jpg", "/clothes/clothe2thumb1.jpg", "/clothes/clothe2thumb2.jpg"],
  },
  {
    id: "f2c25f43-ff4d-4322-83fd-c91e6c3c44aa",
    title: "Black t-shirt with a sweater texture",
    image: "/clothes/clothe3main.jpg",
    price: 31.99,
    originalPrice: 39.99,
    discount: 20,
    rating: 4.0,
    description: "A comfortable black t-shirt with a unique sweater texture,That provides Cozy feelings, perfect for casual outings.",
    colors: ["#F1C40F", "#d2d0d0", "#3498DB"],
    thumbnails: ["/clothes/clothe3main.jpg", "/clothes/clothe3thumb1.jpg", "/clothes/clothe3thumb2.jpg"],
  },
  {
    id: "14d678d9-d137-4ed2-8867-fe782a20ccae",
    title: "Black denim jacket-men",
    image: "/clothes/clothe4main.jpg",
    price: 43.69,
    originalPrice: 45.99,
    discount: 5,
    rating: 3.5,
    description: "This unique piece combines classic denim with a cozy sherpa collar, perfect for adding an extra layer of warmth and flair to any outfit.",
    colors: ["#3357FF", "#2ECC71", "#3498DB"],
    thumbnails: ["/clothes/clothe4main.jpg", "/clothes/clothe4thumb1.jpg", "/clothes/clothe4thumb2.jpg"],
  },
  {
    id: "e4934f5b-df37-4435-9274-4981e53592b9",
    title: "basic zip up hoodie jacket",
    image: "/clothes/clothe5main.jpg",
    price: 28.79,
    originalPrice: 35.99,
    discount: 20,
    rating: 3.5,
    description: "Stay warm and comfy in this Basic Zip Up Hoodie. Crafted with soft cotton, this relaxed fit hoodie is perfect for any casual occasion. Ideal for lounging or layering, it's a must-have addition to your wardrobe.",
    colors: ["#F1C40F", "#000000", "#2ECC71"],
    thumbnails: ["/clothes/clothe5main.jpg", "/clothes/clothe5thumb1.jpg", "/clothes/clothe5thumb2.jpg"],
  },
  {
    id: "6c2d7d43-f67f-4065-8e0b-0100d021ac14",
    title: "embroidered corduroy jacket",
    image: "/clothes/clothe6main.jpg",
    price: 39.09,
    originalPrice: 45.99,
    discount: 15,
    rating: 4.5,
    description: "Introducing our quirky new Corduroy Jacket. With its relaxed fit and unique contrast tipping rib and embroidery detailing, this jacket adds a touch of playfulness to any outfit. Stay comfortable and stylish with this must-have addition to your wardrobe!",
    colors: ["#FF5733", "#d2d0d0", "#3357FF"],
    thumbnails: ["/clothes/clothe6main.jpg", "/clothes/clothe6thumb1.jpg", "/clothes/clothe6thumb2.jpg"],
  },
  {
    id: "127c61a8-4379-44a6-b3bd-58863638ede7",
    title: "black t-shirt with beach graphic",
    image: "/clothes/clothe7main.jpg",
    price: 27.99,
    originalPrice: 39.99,
    discount: 30,
    rating: 4.0,
    description: "A stylish t-shirt with a beach graphic, perfect for summer.",
    colors: ["#33FF57", "#8E44AD", "#2ECC71"],
    thumbnails: ["/clothes/clothe7main.jpg", "/clothes/clothe7thumb1.jpg", "/clothes/clothe7thumb2.jpg"],
  },
  {
    id: "6db305c8-49ba-4614-848f-5b77a2677af6",
    title: "black t-shirt with a unique design",
    image: "/clothes/clothe8main.jpg",
    price: 28.49,
    originalPrice: 29.99,
    discount: 5,
    rating: 3.5,
    description: "This black t-shirt features a unique design that stands out in any crowd. Made from soft, breathable fabric, it's perfect for casual outings or lounging at home.",
    colors: ["#33FF57", "#000000", "#F1C40F"],
    thumbnails: ["/clothes/clothe8main.jpg", "/clothes/clothe8thumb1.jpg", "/clothes/clothe8thumb2.jpg"],
  },
  {
    id: "0854fc4b-4e00-4d9c-8f3b-2d3bffba50fc",
    title: "gray casual jeans",
    image: "/clothes/clothe9main.jpg",
    price: 37.49,
    originalPrice: 49.99,
    discount: 25,
    rating: 5.0,
    description: "casual jeans that are perfect for everyday wear. Made from high-quality cotton, these jeans offer both comfort and style. The gray color adds a modern touch to your wardrobe.",
    colors: ["#000000", "#33FF57", "#d2d0d0"],
    thumbnails: ["/clothes/clothe9main.jpg", "/clothes/clothe9thumb1.jpg", "/clothes/clothe9thumb2.jpg"],
  },
  {
    id: "31c8df12-e1e0-4de8-8023-4f732a16f8c6",
    title: "black denim jeans",
    image: "/clothes/clothe10main.jpg",
    price: 22.09,
    originalPrice: 25.99,
    discount: 15,
    rating: 3.5,
    description: "These black denim jeans are a versatile addition to your wardrobe. Made from durable denim, they offer a comfortable fit and a stylish look. Perfect for casual outings or dressing up with a blazer.",
    colors: ["#3498DB", "#8E44AD", "#3357FF"],
    thumbnails: [
      "/clothes/clothe10main.jpg",
      "/clothes/clothe10thumb1.jpg",
      "/clothes/clothe10thumb2.jpg",
    ],
  },
  {
    id: "5379097b-b8ae-4d03-a59a-a555ab246232",
    title: "blue and white cross graphic shirt",
    image: "/clothes/clothe11main.jpg",
    price: 37.99,
    originalPrice: 39.99,
    discount: 5,
    rating: 3.5,
    description: "This blue and white cross graphic shirt is a stylish addition to your wardrobe. Made from soft, breathable fabric, it's perfect for casual outings or lounging at home.",
    colors: ["#3357FF", "#8E44AD", "#000000"],
    thumbnails: [
      "/clothes/clothe11main.jpg",
      "/clothes/clothe11thumb1.jpg",
      "/clothes/clothe11thumb2.jpg",
    ],
  },
  {
    id: "5dbdf425-54df-4dbd-95fd-50876c5ac53b",
    title: "Basic cross pattern shirt",
    image: "/clothes/clothe12main.jpg",
    price: 26.99,
    originalPrice: 29.99,
    discount: 10,
    rating: 4.0,
    description: "This is a basic orange brown crossed shirt made with cotton-silk perfect for casual outings.",
    colors: ["#33FF57", "#d2d0d0", "#8E44AD"],
    thumbnails: [
      "/clothes/clothe12main.jpg",
      "/clothes/clothe12thumb1.jpg",
      "/clothes/clothe12thumb2.jpg",
    ],
  },
  {
    id: "0b2b2156-ad5c-4cdc-96ed-7fce3a5e845c",
    title: "white and brown striped shirt",
    image: "/clothes/clothe13main.jpg",
    price: 15.99,
    originalPrice: 19.99,
    discount: 20,
    rating: 4.5,
    description: "This is a white and brown striped shirt made with cotton-silk perfect for casual outings.",
    colors: ["#3357FF", "#F1C40F", "#FF5733"],
    thumbnails: [
      "/clothes/clothe13main.jpg",
      "/clothes/clothe13thumb1.jpg",
      "/clothes/clothe13thumb2.jpg",
    ],
  },
  {
    id: "3d13a30a-d0dd-4a1e-a7cf-7ad05b089cc2",
    title: "beli eve graphic shirt",
    image: "/clothes/clothe14main.jpg",
    price: 26.99,
    originalPrice: 35.99,
    discount: 25,
    rating: 5.0,
    description: "This is a fun shirt with green graphic to it perfect for parties or functions",
    colors: ["#33FF57", "#000000", "#F1C40F"],
    thumbnails: [
      "/clothes/clothe14main.jpg",
      "/clothes/clothe14thumb1.jpg",
      "/clothes/clothe14thumb2.jpg",
    ],
  },
  {
    id: "126455af-4f62-46f5-8ba4-d7278d8267d4",
    title: "plain light blue sweater",
    image: "/clothes/clothe15main.jpg",
    price: 18.99,
    originalPrice: 19.99,
    discount: 5,
    rating: 5.0,
    description: "This is a plain light blue sweater made with cotton perfect for casual wear",
    colors: ["#3498DB", "#8E44AD", "#33FF57"],
    thumbnails: [
      "/clothes/clothe15main.jpg",
      "/clothes/clothe15thumb1.jpg",
      "/clothes/clothe15thumb2.jpg",
    ],
  },
  {
    id: "c125c811-d8fd-4bbc-a3bb-74081b4bd97f",
    title: "blue pants",
    image: "/clothes/clothe16main.jpg",
    price: 13.99,
    originalPrice: 19.99,
    discount: 30,
    rating: 4.0,
    description: "This is a casual pants with plain blue color made with silk perfect for casual outings.",
    colors: ["#8E44AD", "#000000", "#3498DB"],
    thumbnails: [
      "/clothes/clothe16main.jpg",
      "/clothes/clothe16thumb1.jpg",
      "/clothes/clothe16thumb2.jpg",
    ],
  },
  {
    id: "ca9ed656-5d7b-4e1b-a375-40ba71a11d12",
    title: "white pajamas",
    image: "/clothes/clothe17main.jpg",
    price: 20.99,
    originalPrice: 29.99,
    discount: 30,
    rating: 4.5,
    description: "These are plain white pajamas made with cotton perfect for comfortable sleep.",
    colors: ["#FF5733", "#8E44AD", "#d2d0d0"],
    thumbnails: [
      "/clothes/clothe17main.jpg",
      "/clothes/clothe17thumb1.jpg",
      "/clothes/clothe17thumb2.jpg",
    ],
  },
  {
    id: "36c6622d-6b00-4c78-94d8-4013653fba80",
    title: "red-brown denim jeans",
    image: "/clothes/clothe18main.jpg",
    price: 35.99,
    originalPrice: 39.99,
    discount: 10,
    rating: 3.5,
    description: "This is a reddish brown denim jeans made with high-quality denim fabric. Perfect for casual outings or dressing up.",
    colors: ["#3498DB", "#8E44AD", "#2ECC71"],
    thumbnails: [
      "/clothes/clothe18main.jpg",
      "/clothes/clothe18thumb1.jpg",
      "/clothes/clothe18thumb2.jpg",
    ],
  },
  {
    id: "7df30784-a668-4d2e-9f8f-0fe8bc9a858b",
    title: "white hoddie",
    image: "/clothes/clothe19main.jpg",
    price: 24.69,
    originalPrice: 25.99,
    discount: 5,
    rating: 4.5,
    description: "This is a plain white hoddie jacket made with cotton fabric, is extremely soft and comfortable.",
    colors: ["#8E44AD", "#FF5733", "#3498DB"],
    thumbnails: [
      "/clothes/clothe19main.jpg",
      "/clothes/clothe19thumb1.jpg",
      "/clothes/clothe19thumb2.jpg",
    ],
  },
  {
    id: "1633dbed-4a6e-458c-a0c6-668543bb1d2e",
    title: "black and gray hoddie",
    image: "/clothes/clothe20main.jpg",
    price: 32.19,
    originalPrice: 45.99,
    discount: 30,
    rating: 5.0,
    description: "This is a black and gray hoddie with unique design made with cotton fabric, is extremely soft and comfortable.",
    colors: ["#33FF57", "#2ECC71", "#3498DB"],
    thumbnails: [
      "/clothes/clothe20main.jpg",
      "/clothes/clothe20thumb1.jpg",
      "/clothes/clothe20thumb2.jpg",
    ],
  },
  {
    id: "afba40b9-3d75-42bd-8f36-385394af8aa2",
    title: "tin graphic hoddie",
    image: "/clothes/clothe21main.jpg",
    price: 33.99,
    originalPrice: 39.99,
    discount: 15,
    rating: 5.0,
    description: "This is a tin coloured hoddie with ZERO THREE ACADEMY graphic printed on it, made with cotton fabric, is extremely soft and comfortable.",
    colors: ["#8E44AD", "#3357FF", "#33FF57"],
    thumbnails: [
      "/clothes/clothe21main.jpg",
      "/clothes/clothe21thumb1.jpg",
      "/clothes/clothe21thumb2.jpg",
    ],
  },
  {
    id: "134f3627-8eeb-4405-ae17-bd9bf959b359",
    title: "BLACK graphic hoddie",
    image: "/clothes/clothe22main.jpg",
    price: 34.19,
    originalPrice: 35.99,
    discount: 5,
    rating: 3.5,
    description: "This is a black hoddie with unique design made with cotton fabric, is extremely soft and comfortable.",
    colors: ["#33FF57", "#FF5733", "#2ECC71"],
    thumbnails: [
      "/clothes/clothe22main.jpg",
      "/clothes/clothe22thumb1.jpg",
      "/clothes/clothe22thumb2.jpg",
    ],
  },
  {
    id: "bf02f39f-e15d-4772-88d1-62571ad82827",
    title: "basic black sweater",
    image: "/clothes/clothe23main.jpg",
    price: 50.99,
    originalPrice: 59.99,
    discount: 15,
    rating: 3.5,
    description: "This is a basic black sweater made with high-quality cotton fabric, is extremely soft and warm , perfect for winter wear.",
    colors: ["#8E44AD", "#d2d0d0", "#000000"],
    thumbnails: [
      "/clothes/clothe23main.jpg",
      "/clothes/clothe23thumb1.jpg",
      "/clothes/clothe23thumb2.jpg",
    ],
  },
  {
    id: "c4894212-434a-49e4-bc54-f4d9843500c6",
    title: "basic white sweater",
    image: "/clothes/clothe24main.jpg",
    price: 18.19,
    originalPrice: 25.99,
    discount: 30,
    rating: 4.5,
    description: "This is a basic white sweater with a simple and elegant design without sleeves, made with high-quality cotton fabric. It is extremely soft and warm, perfect for winter wear.",
    colors: ["#8E44AD", "#F1C40F", "#3498DB"],
    thumbnails: [
      "/clothes/clothe24main.jpg",
      "/clothes/clothe24thumb1.jpg",
      "/clothes/clothe24thumb2.jpg",
    ],
  },
  {
    id: "d62e579b-3a8f-48c4-bc15-80ac7cd30759",
    title: "basic black sweater",
    image: "/clothes/clothe25main.jpg",
    price: 30.59,
    originalPrice: 35.99,
    discount: 15,
    rating: 5.0,
    description: "This is a basic black sweater made with high-quality cotton fabric, is extremely soft and warm , perfect for winter wear.",
    colors: ["#8E44AD", "#33FF57", "#2ECC71"],
    thumbnails: [
      "/clothes/clothe25main.jpg",
      "/clothes/clothe25thumb1.jpg",
      "/clothes/clothe25thumb2.jpg",
    ],
  },
];